name: cdk

on:
  push:
    branches:
      - main
jobs:
  aws_cdk:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Setup dependencies
        run: cd cdk && npm ci

      - name: Deploy
        run: cd cdk && cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: "ap-northeast-1"
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
